"""Build data/catalogs/author_profiles.json for library.html's Anukramani view.

For every author in the Dvaita Grantha Anukramani catalogue, attach the
guru-parampara person (if any) so the library can show who wrote a work:
period, matha, guru, role, place, contribution.

Matching, strongest first:
  1. data/catalogs/author_works_index.json  byPerson[*].authorIds (confirmed)
  2. a normalised-name match of the catalogue author against parampara node
     names, accepted ONLY when it is unambiguous (exactly one node).
Anything else is left unmatched -- an unmatched author simply shows no bio,
which is better than a wrong one.
"""
import json, re, unicodedata, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8')

def norm(s):
    s = unicodedata.normalize('NFD', (s or '').lower())
    s = ''.join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r'\(.*?\)', '', s)
    s = s.replace('ṃ', 'n').replace('ṅ', 'n').replace('m̐', 'n')
    s = re.sub(r'[^a-z]', '', s)
    for a, b in (('sh', 's'), ('ee', 'i'), ('oo', 'u'), ('aa', 'a'), ('th', 't'), ('w', 'v'),
                 ('ii', 'i'), ('uu', 'u')):
        s = s.replace(a, b)
    s = re.sub(r'^(srimad|srimat|sri|svami|swami)+', '', s)
    s = re.sub(r'(tirtha|tirt|yati|swami|svami|charya|acarya|acaryah|ayya)+', '', s)
    s = re.sub(r'(ah|aha|a|h|m)+$', '', s)
    return s

cat = json.load(open('data/catalogs/dvaita_grantha_anukramani.json', encoding='utf8'))
idxf = json.load(open('data/catalogs/author_works_index.json', encoding='utf8'))
para = json.load(open('guru-parampara/data/parampara.json', encoding='utf8'))
nodes = {n['id']: n for n in para['nodes']}
# Names too common / ambiguous for the automatic match, or spelled several ways
# in the sheet, decided once by hand. Key = norm(name).
MANUAL = {'anand': 'madhva', 'madhv': 'madhva', 'sumatindr': 'sumatindra'}
PEOPLE = {'acharya', 'dasa', 'scholar', 'guru'}   # never match a deity or sage by name
byname = {}
for n in para['nodes']:
    if n.get('tag') in PEOPLE:
        byname.setdefault(norm(n['name']), []).append(n['id'])
for n in para['nodes']:
    for t in (n.get('titles') or []) if n.get('tag') in PEOPLE else []:
        byname.setdefault(norm(t), []).append(n['id'])

confirmed = {}
for pid, v in idxf['byPerson'].items():
    for aid in v.get('authorIds', []):
        confirmed[aid] = pid

out, report = {}, []
for a in cat['masters']['authors']:
    pid, how = confirmed.get(a['id']), 'confirmed'
    if not pid and norm(a['iast']) in MANUAL:
        pid, how = MANUAL[norm(a['iast'])], 'manual'
    if not pid:
        cands = set(byname.get(norm(a['iast']), []))
        if len(cands) == 1 and len(norm(a['iast'])) >= 4:
            pid, how = next(iter(cands)), 'name'
            # a lay ācārya must not borrow a pontiff's bio (Gopālācārya != Gopālasvāmi Tīrtha)
            plain = unicodedata.normalize('NFD', a['iast'].lower())
            if 'carya' in ''.join(c for c in plain if not unicodedata.combining(c))                     and 'carya' not in nodes[pid]['name'].lower():
                pid = None
    if not pid or pid not in nodes:
        continue
    n = nodes[pid]
    out[a['id']] = {'person': pid, 'via': how, 'name': n['name'], 'period': n.get('period'),
                    'matha': n.get('matha'), 'guru': n.get('guru'), 'role': n.get('role'),
                    'place': n.get('place'), 'brindavana': n.get('brindavana'),
                    'purva': n.get('purva'), 'titles': n.get('titles') or [],
                    'contrib': n.get('contrib'), 'works': n.get('works') or []}
    report.append((a['count'], a['canonical'], n['name'], how))

gurus = {p['guru']: nodes[p['guru']]['name'] for p in out.values() if p.get('guru') in nodes}
json.dump({'schema': 'author_profiles_v1',
           'note': 'GENERATED by tools/build_author_profiles.py from parampara.json -- do not hand-edit.',
           'mathaLabels': para['matha_labels'], 'gurus': gurus, 'profiles': out},
          open('data/catalogs/author_profiles.json', 'w', encoding='utf8'),
          ensure_ascii=False, separators=(',', ':'))
report.sort(reverse=True)
for r in report: print(*r)
print(len(out), 'of', len(cat['masters']['authors']), 'authors matched;', sum(r[0] for r in report), 'works')
