#!/usr/bin/env python3
"""Which Harikathamrtasara padyas are missing which commentary layer.

The Harikathamrtasara carries nine commentary layers, and no padya carries all
nine. This reports two different kinds of gap, because they need different work:

  * a padya with NO commentary at all -- 86 of them, and two entire sandhis
    (26 Avarohana Taratamya, 27 Anukramanika Taratamya) where not one padya
    has a single layer. A whole-sandhi hole is almost always a scan that was
    never OCRed, not a book that omits the passage.
  * a padya missing SOME layers -- expected and usually not a defect. The
    Bhavadarshana covers 168 padyas because that is what its author wrote,
    not because 842 padyas failed to extract.

Emits JSON (machine-readable, for the re-run) and Markdown (for a human to
read against the printed volumes). Regenerate after any HKS OCR run:

    python3 tools/hks_commentary_gaps.py
"""
import json, os, sys, collections

HKS = "data/Tattvavada/Itara/DasaSahitya/harikathamrutasara/data.json"
OUT_JSON = "admin/config/hks_commentary_gaps.json"
OUT_MD = "docs/HKS_COMMENTARY_GAPS.md"

# Printed Kannada names, so the report reads the way the volumes do.
LAYERS = [
    ("vyakhyana", "ವ್ಯಾಖ್ಯಾನ"),
    ("sarvavyakhyana_sara_sangraha", "ಸರ್ವವ್ಯಾಖ್ಯಾನಸಾರಸಂಗ್ರಹ"),
    ("pratipadartha", "ಪ್ರತಿಪದಾರ್ಥ"),
    ("sankarshana_odeyara_vyakhyana", "ಶ್ರೀಸಂಕರ್ಷಣ ಒಡೆಯರ ವ್ಯಾಖ್ಯಾನ"),
    ("bhavaprakashika", "ಭಾವಪ್ರಕಾಶಿಕೆ"),
    ("guruhrdaya_prakashika", "ಶ್ರೀಗುರುಹೃದಯಪ್ರಕಾಶಿಕೆ"),
    ("vyasadasa_siddhanta_kaumudi", "ಶ್ರೀವ್ಯಾಸದಾಸ ಸಿದ್ಧಾಂತ ಕೌಮುದೀ"),
    ("bhavadarpana", "ಭಾವದರ್ಪಣ"),
    ("bhavadarshana", "ಭಾವದರ್ಶನ"),
]


def load(root):
    with open(os.path.join(root, HKS), encoding="utf-8") as fh:
        return json.load(fh)["items"]


def analyse(items):
    per_sandhi = collections.OrderedDict()
    bare, partial = [], []
    layer_counts = collections.Counter()

    for it in items:
        sn = it.get("sandhi_number")
        row = per_sandhi.setdefault(sn, {
            "sandhi_number": sn,
            "sandhi_title": (it.get("sandhi_title") or "").split(" / ")[0],
            "padyas": 0, "with_any": 0, "bare": [],
        })
        row["padyas"] += 1
        comm = it.get("commentaries") or {}
        present = [k for k, _ in LAYERS if comm.get(k)]
        for k in present:
            layer_counts[k] += 1
        if present:
            row["with_any"] += 1
            missing = [k for k, _ in LAYERS if not comm.get(k)]
            if missing:
                partial.append({"id": it.get("id"), "sandhi": sn,
                                "has": present, "missing": missing})
        else:
            row["bare"].append(it.get("id"))
            bare.append({"id": it.get("id"), "sandhi": sn,
                         "sandhi_title": row["sandhi_title"]})
    return per_sandhi, bare, partial, layer_counts


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    items = load(root)
    per_sandhi, bare, partial, layer_counts = analyse(items)
    total = len(items)

    empty_sandhis = [r for r in per_sandhi.values() if r["with_any"] == 0]

    payload = {
        "_readme": [
            "Harikathamrtasara commentary gaps, regenerated by",
            "tools/hks_commentary_gaps.py. 'bare' padyas carry no commentary of",
            "any kind and are the real work queue; 'partial' padyas are missing",
            "some layers, which is usually what the printed book does too.",
        ],
        "total_padyas": total,
        "padyas_with_any_commentary": total - len(bare),
        "padyas_with_no_commentary": len(bare),
        "sandhis_with_no_commentary_at_all": [
            {"sandhi_number": r["sandhi_number"], "sandhi_title": r["sandhi_title"],
             "padyas": r["padyas"]} for r in empty_sandhis],
        "layer_coverage": {k: layer_counts[k] for k, _ in LAYERS},
        "bare_padyas": bare,
        "by_sandhi": [
            {k: v for k, v in r.items()} for r in per_sandhi.values()],
    }
    with open(os.path.join(root, OUT_JSON), "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write("\n")

    L = []
    L.append("# Harikathāmṛtasāra — where the commentary is missing\n")
    L.append("Generated by `tools/hks_commentary_gaps.py`. Regenerate after any HKS OCR run.\n")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| padyas | %d |" % total)
    L.append("| carry at least one commentary | %d |" % (total - len(bare)))
    L.append("| **carry none at all** | **%d** |" % len(bare))
    L.append("")
    if empty_sandhis:
        L.append("## Sandhis with no commentary whatsoever\n")
        L.append("A whole sandhi with nothing is a scan gap, not an editorial choice.\n")
        L.append("| sandhi | title | padyas |")
        L.append("|---|---|---|")
        for r in empty_sandhis:
            L.append("| %s | %s | %d |" % (r["sandhi_number"], r["sandhi_title"], r["padyas"]))
        L.append("")
    L.append("## Layer coverage\n")
    L.append("| layer | padyas | of %d |" % total)
    L.append("|---|---|---|")
    for k, name in LAYERS:
        n = layer_counts[k]
        L.append("| %s | %d | %d%% |" % (name, n, round(100.0 * n / total)))
    L.append("")
    L.append("## Padyas with no commentary, by sandhi\n")
    for r in per_sandhi.values():
        if not r["bare"]:
            continue
        L.append("**%s — %s** (%d of %d padyas bare)\n" % (
            r["sandhi_number"], r["sandhi_title"], len(r["bare"]), r["padyas"]))
        L.append("`" + "`, `".join(r["bare"]) + "`\n")
    with open(os.path.join(root, OUT_MD), "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))

    print("padyas                     %d" % total)
    print("with at least one layer    %d" % (total - len(bare)))
    print("with NO commentary at all  %d" % len(bare))
    print("sandhis entirely bare      %d  %s" % (
        len(empty_sandhis), [r["sandhi_number"] for r in empty_sandhis]))
    print("partially covered padyas   %d" % len(partial))
    print("\nwrote %s\nwrote %s" % (OUT_JSON, OUT_MD))
    return 0


if __name__ == "__main__":
    sys.exit(main())
