#!/usr/bin/env python3
"""
rebuild_sarvam_missing.py -- regenerate admin/config/ocr_sarvam_missing.json
from the staged files themselves.

That ledger is what tools/redispatch_sarvam.py spends money from, and it
was generated by hand on 18 Sep. Nothing regenerated it. So the moment a
re-dispatch succeeds the ledger is stale in the most expensive possible
direction: it still lists pages that have since come back, and the next
run pays for them again. One of this repo's own commits is titled "Stop
re-paying for pages earlier runs already resolved" -- this is the tool
that should have prevented needing it.

Read from the staged JSON, never from workflow exit codes. Every one of
the original 5,342 missing pages sat under a run that reported success:
sarvam_docai.py used to keep calling after the first 402 and record each
page as {"ok": false, "error": "HTTP Error 402: Payment Required"} while
the job exited 0. The staged file is the only honest record of what
actually came back.

Runs offline: git ls-tree / git cat-file against the ocr-staging refs
already on disk. Nothing is fetched and no branch is touched.

  python3 tools/rebuild_sarvam_missing.py            # report the delta
  python3 tools/rebuild_sarvam_missing.py --write
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / "admin/config/ocr_sarvam_missing.json"


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", str(ROOT), *args],
                          capture_output=True, text=True).stdout


def to_ranges(pages: list[int]) -> list[str]:
    if not pages:
        return []
    pages = sorted(set(pages))
    spans, start, prev = [], pages[0], pages[0]
    for p in pages[1:]:
        if p == prev + 1:
            prev = p
            continue
        spans.append((start, prev))
        start = prev = p
    spans.append((start, prev))
    return [str(a) if a == b else f"{a}-{b}" for a, b in spans]


def scan() -> dict[str, list[dict]]:
    """Which pages of each work still have no usable OCR.

    A page counts as missing when its entry says ok is false or carries an
    error. Emptiness alone is NOT missing: a blank verso comes back as
    {"ok": true, "blocks_count": 0, "html": ""}, which is Sarvam correctly
    reporting that there is nothing on the page. It was delivered and
    billed, and re-sending it buys another empty string. Ten such pages --
    in vaidika_svara, hks 11/12/21/22/24/28, brhatisahasram and
    chandogya -- were flagged as missing by an earlier version of this rule
    that treated empty as failed.

    Crucially this is resolved ACROSS FILES, not within one. A re-dispatch
    writes a NEW file named for the range it was asked for
    (sarvam_pages300-309.json), while the original file
    (sarvam_pages210-409.json) keeps its failed entries forever. Counting
    per-file therefore reports a page as missing even after it has been
    re-fetched and paid for -- which is precisely the double-payment this
    tool exists to prevent. So every file for a work is read first, a page
    is missing only if NO file has it succeeding, and the surviving gaps
    are attributed back to the file that first reported them.
    """
    # work -> {"ok": set[int], "bad": {page: (file, url, language)}}
    acc: dict[str, dict] = {}
    branches = [b.strip() for b in git("branch", "-r").splitlines()
                if "ocr-staging/" in b and "->" not in b]
    seen: set[tuple[str, str]] = set()
    for br in branches:
        listing = git("ls-tree", "-r", "--name-only", br, "--", "data/ocr_staging/")
        for path in listing.split():
            name = path.rsplit("/", 1)[-1]
            if not (name.startswith("sarvam_") and name.endswith(".json")):
                continue
            work = path.split("/")[2]
            if (work, name) in seen:
                continue
            seen.add((work, name))
            try:
                blob = json.loads(git("cat-file", "-p", f"{br}:{path}"))
            except (json.JSONDecodeError, ValueError):
                continue
            if not isinstance(blob, dict):
                continue
            src = blob.get("source") or {}
            meta = (name,
                    src.get("pdf") or src.get("pdf_url") or src.get("url") or "",
                    blob.get("language") or "sa-IN")
            a = acc.setdefault(work, {"ok": set(), "bad": {}})
            for pg in blob.get("pages") or []:
                if not isinstance(pg, dict) or pg.get("page") is None:
                    continue
                n = int(pg["page"])
                text = pg.get("html") or pg.get("text") or ""
                delivered = pg.get("ok") is not False and not pg.get("error")
                if delivered:
                    # Empty but delivered: a blank page. Counts as done.
                    a["ok"].add(n)
                else:
                    a["bad"].setdefault(n, meta)

    works: dict[str, list[dict]] = {}
    for work, a in acc.items():
        still = {n: m for n, m in a["bad"].items() if n not in a["ok"]}
        if not still:
            continue
        by_file: dict[tuple, list[int]] = {}
        for n, m in still.items():
            by_file.setdefault(m, []).append(n)
        works[work] = [
            {"file": f, "pages": len(ps), "ranges": to_ranges(ps),
             "url": u, "language": lang}
            for (f, u, lang), ps in sorted(by_file.items())]
    return works


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    fresh = scan()
    total = sum(f["pages"] for fs in fresh.values() for f in fs)

    old = json.loads(LEDGER.read_text()) if LEDGER.exists() else {"works": {}}
    old_total = old.get("total_pages_missing", 0)
    print(f"ledger says : {old_total} pages across {len(old.get('works', {}))} works")
    print(f"staged says : {total} pages across {len(fresh)} works")
    delta = old_total - total
    print(f"resolved    : {delta} pages  (about Rs{delta * 0.44:.2f} that would "
          f"otherwise be paid for twice)" if delta > 0 else
          f"difference  : {delta}")

    gone = sorted(set(old.get("works", {})) - set(fresh))
    if gone:
        print(f"\nworks now complete ({len(gone)}):")
        for w in gone:
            print(f"      {w}")

    if args.write:
        LEDGER.write_text(json.dumps({
            "_readme": [
                "Sarvam pages that were requested and did not come back.",
                "Re-dispatch with tools/redispatch_sarvam.py once the prepaid",
                "balance at dashboard.sarvam.ai covers them.",
                "Regenerated by tools/rebuild_sarvam_missing.py from the staged",
                "sarvam_*.json files themselves, NOT from workflow exit codes --",
                "the original 5,342 all sat under runs that reported success.",
            ],
            "total_pages_missing": total,
            "works": fresh,
        }, ensure_ascii=False, indent=1) + "\n")
        print(f"\nwrote {LEDGER.relative_to(ROOT)}")
    else:
        print("\n(report only -- pass --write to update the ledger)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
